<a href="https://colab.research.google.com/github/TDoi-99726/statistical_learning_with_python/blob/master/biling_log.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import collections

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# データ読み込み

In [ ]:
#basicinfo = pd.read_csv("basicinfo.csv")
#basicinfo_ids = list(basicinfo["調査ID"])
#print(basicinfo_ids)

pcdf = pd.read_csv("/content/drive/Shareddrives/課金調査/コード/入力/PC.csv")
pcids = list(pcdf["調査ID"])
print(pcids)

phonedf = pd.read_csv("/content/drive/Shareddrives/課金調査/コード/入力/smartphone.csv")
phoneids = list(phonedf["調査ID"])
print(phoneids)

['bular', 'AYTK416', '村紗 楓', 'gonpati', '八坂＠', 'neuconmsi', 'K.Unno', 'Merry21', 'jro33', 'takataka20', 'Miyako21', 'worksdellta2021', 'elahrairah5', 'sitou33tM', 'budoubox', 'dorahowl', 'momokan13']
['AYTK416', 'ryota3510', 'popo02', 'yukimonma0111', 'Pero24', '麻生 まち.*･ﾟ', 'Nattoufu', 'suika2288', '上野輪', 'nozaki@', 'www088759', 'おふとん103', 'tanaka_6231', 'pereo', 'meimei08', '217karin', 'Ichi355', 'takashimu666', 'yuki643499', '八坂＠', 'kinokado', '猫柳はる', 'aya6969', 'Sakuramine77', 'doctall12', 'K1515r', 'Tamura1212', 'coffee.deeep', 'YUYU0703', 'tn_english', 'twak529tmak', 'konin', '荒木11242', 'surimi', 'Monti0918', 'chi.da.', 'nyannyan_k', 'suntake', 'fox3939', 'senburiteana27', '左近\u3000剛', 'mokara', 'naaaachandayooo', 'takabayashiriku', 'raven0078', 'httgs_dr', 'Masaya_11', 'kotohiki', 'tensonsan', 'tskyio', 'Chirasama', 'worksdellta2021', '金陵おいしいよ', 'masa124k', 'mi_remo', 'miyufrog', 'huntinghunter716', 'tanakaleon', 'mihosan34', 'ok_2188', 'morikoha0206', 'いこや', '長谷部杏菜', 'psrn', 'zark', 'Webs1nj1', '縄内\u3000仁', 'seigai', 'lmamol', 'ryouta.bad', '蒼海じゅん', 'NAVI66', 'BeeYuno0840', 'CdyCottonwt', 'denden1029', 'nami__', 'ginnan_66', 'しまちゃん♪', 'sopid3605', 'yuya000704', 'eizumi0921', 'luismiulito', 'ikejima', 'shshinnosuke', '嘉数ひなみ', 'カカオ1122', 'tsujiuchi0612', 'shirokurocoin', 'カルパス2022', 'marlmisowasabi', '0807qaz0807', 'ゆきぞー', 'tonkkko6021', 'cw_satou', 'yusaku4665', 'NSNS1995', 'takidai99', 'mutkun0403', 'haikikun']

In [ ]:
phonedf

,Unnamed: 0,タイムスタンプ,調査ID,2021/2/24,2021/2/25,2021/2/26,2021/2/27,2021/2/28,2021/3/1,2021/3/2,...,2022/9/21,2022/9/22,2022/9/23,2022/9/24,2022/9/25,2022/9/26,2022/9/27,2022/9/28,2022/9/29,2022/9/30
0,1.0,2022/11/11 10:52:57 午前 GMT+9,AYTK416,NaN,NaN,NaN,2080.0,NaN,NaN,2080.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,2022/11/11 10:54:07 午前 GMT+9,ryota3510,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1.0,2022/11/11 10:54:35 午前 GMT+9,popo02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1.0,2022/11/11 10:58:04 午前 GMT+9,yukimonma0111,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1.0,2022/11/11 11:00:33 午前 GMT+9,Pero24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,1.0,2022/12/1 20:35,yusaku4665,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95,NaN,2022/12/4 9:37,NSNS1995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,1.0,2022/12/4 19:04,takidai99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,NaN,2022/12/5 9:41,mutkun0403,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,NaN,2022/12/5 12:24,haikikun,NaN,NaN,NaN,NaN,2080.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
pcdf

,Unnamed: 0,タイムスタンプ,調査ID,2021/2/24,2021/2/25,2021/2/26,2021/2/27,2021/2/28,2021/3/1,2021/3/2,...,2022/9/21,2022/9/22,2022/9/23,2022/9/24,2022/9/25,2022/9/26,2022/9/27,2022/9/28,2022/9/29,2022/9/30
0,1,2022/11/11 10:53:37 午前 GMT+9,bular,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2022/11/11 11:00:58 午前 GMT+9,AYTK416,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,2022/11/11 5:54:11 午後 GMT+9,村紗 楓,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,2022/11/11 10:13:14 午後 GMT+9,gonpati,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,2022/11/12 4:22:21 午後 GMT+9,八坂＠,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1,2022/11/13 5:22:59 午後 GMT+9,neuconmsi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,980.0,NaN,NaN,NaN,NaN,NaN,NaN
6,1,2022/11/16 4:31:38 午後 GMT+9,K.Unno,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1,2022/11/16 5:33:52 午後 GMT+9,Merry21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2080.0
8,1,2022/11/18 2:52:00 午後 GMT+9,jro33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1,2022/11/19 8:37:34 午前 GMT+9,takataka20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,1,2022/11/21 8:03:29 午後 GMT+9,Miyako21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,1,2022/11/22 18:50,worksdellta2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,1,2022/11/22 19:00,elahrairah5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,1,2022/11/24 5:59,sitou33tM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,1,2022/11/24 14:40,budoubox,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,1,2022/11/27 19:17,dorahowl,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,1,2022/11/29 17:48,momokan13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,980.0,NaN,NaN,NaN,NaN

In [ ]:
#転置
pcdf = pcdf.drop(["タイムスタンプ","Unnamed: 0"],axis=1).set_index("調査ID")
phonedf = phonedf.drop(["タイムスタンプ","Unnamed: 0"],axis=1).set_index("調査ID")
pcdf = pcdf.T
pcdf = pcdf.fillna(0)
phonedf = phonedf.T
phonedf = phonedf.fillna(0)

In [ ]:
for id in pcids:
    if id not in phoneids:
        phonedf = pd.concat([pcdf[id],phonedf],axis=1)
    else:
        print(id)
        phonedf[id] = phonedf[id] + pcdf[id]

AYTK416
八坂＠
worksdellta2021

In [ ]:
phonedf

,momokan13,dorahowl,budoubox,sitou33tM,elahrairah5,Miyako21,takataka20,jro33,Merry21,K.Unno,...,marlmisowasabi,0807qaz0807,ゆきぞー,tonkkko6021,cw_satou,yusaku4665,NSNS1995,takidai99,mutkun0403,haikikun
2021/2/24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2021/2/25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2021/2/26,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2021/2/27,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2021/2/28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2080.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022/9/26,980.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2022/9/27,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2022/9/28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2022/9/29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2022/9/30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2080.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
phonedf.to_csv("/content/drive/Shareddrives/課金調査/コード/csvファイル/課金ログ/billing_log.csv")